volumes:  # создаем постоянное внутреннее хранилище для записей бд
  db_data:

services:
  db:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0  # конкретная версия
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql  # данные сохраняются в volume
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # readonly
    # доступа к базе данных извне нет, только внутри сети, в крайнем случае можно открыть доступ с localhost
    healthcheck:  # проверка готовности бд
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 40s
    restart: unless-stopped  # не перезапускается после череды ошибок или ручной остановки


  app:
    build: .
    container_name: predict-app
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}  # пароли в файле .env
    # доступа к приложению извне нет, только через nginx
    depends_on:
      db:
        condition: service_healthy  # доступ только по готовности
    restart: unless-stopped  # не перезапускается после череды ошибок или ручной остановки


  nginx:
    image: nginx:1.25-alpine  # конкретная версия
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # readonly
    depends_on:
      - app
    restart: unless-stopped  # не перезапускается после череды ошибок или ручной остановки
