# нет версии
# нет постоянного хранилища для записей бд

services:
  db:
    image: mysql:latest  # версия latest
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # пароли в явном виде
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:  # данные теряются при перезапуске контейнера
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"  # доступ к базе данных извне
    restart: always  # будет перезапускаться даже при остановке с ошибкой (риск зацикливания)


  app:
    build: .
    container_name: predict-app
    environment:
      DB_HOST: db
      DB_NAME: app_db
      DB_USER: app_user
      DB_PASSWORD: app_password
    ports:
      - "5000:5000"  # доступ не только через nginx
    depends_on:
      - db  # нет healthcheck
    restart: always  # будет перезапускаться даже при остановке с ошибкой


  nginx:
    image: nginx:latest  # версия latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always  # будет перезапускаться даже при остановке с ошибкой